ablog/ablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('theblog.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ablog/members/urls.py
from django.urls import path
from members.views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfilePageView, EditProfilePageView, CreateProfilePageView
#from django.contrib.auth import views as auth_views
from . import views

app_name = 'members'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    #path('password/', auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html')),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html')),
    path('password_success', views.password_success, name="password_success"),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name='show_profile_page'),
    path('<int:pk>/edit_profile_page/', EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page/', CreateProfilePageView.as_view(), name='create_profile_page'),
]

ablog/theblog/urls.py
from django.urls import path
#from . import views
from theblog.views import HomeView, ArticleDetailView, AddPostView, UpdatePostView,\
    DeletePostView, AddCategoryView, CategoryView, LikeView, AddCommentView

app_name = 'theblog'

urlpatterns = [
    #path('', views.home, name="home"),
    path('', HomeView.as_view(), name="home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name="article-detail"),
    path('add_post/', AddPostView.as_view(), name="add_post"),
    path('add_category/', AddCategoryView.as_view(), name="add_category"),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name="update_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),
    path('category/<str:cats>/', CategoryView, name="category"),
    #path('<str:cats>/', CategoryView, name="category"),
    #path('category-list/', CategoryListView, name="category-list"),
    path('like/<int:pk>', LikeView, name="like_post"),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name="add_comment"),
]

ablog/theblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField
"""
admin kısmında groups ve users gibi post kısmı da görmemizi sağlar.
postun altında tanımladığımız title, author ve body kısımları yer alıyor.
"""


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('theblog:home')


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    website_url = models.CharField(max_length=255, null=True, blank=True)
    facebook_url = models.CharField(max_length=255, null=True, blank=True)
    twitter_url = models.CharField(max_length=255, null=True, blank=True)
    instagram_url = models.CharField(max_length=255, null=True, blank=True)
    pinterest_url = models.CharField(max_length=255, null=True, blank=True)
    mail_to = models.CharField(max_length=255, null=True, blank=True)


    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('theblog:home')

class Post(models.Model):
    """
    default="My Blog!" özelliğini sonradan iptal ettik
    models.CASCADE kullanıcıların oluşturduğu blogları silmeye yarar.
    bir kullanıcı hesabı silindiğinde,
    bu kullanıcıya ait tüm Author (yazar) nesneleri de silinecektir.
    "author" alanı, "User" modeline bir ForeignKey alanıdır.
    Yani, bir "Post" modeli oluşturulurken,
    "author" alanına yalnızca "User" modelinde tanımlanmış bir kullanıcı atanabilir.
    """
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="images/")
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #body = models.TextField()
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255, default='coding')
    likes = models.ManyToManyField(User, related_name="blog_posts", blank=True)


    # Bu yöntem, "Post" nesnesinin başlığını ve yazarını içeren bir dize döndürür.
    def __str__(self):
        """
        self.author bir obje olduğu için onu strye çevirdik.
        title ve post isimleriyle görmemizi sağlar.
        """
        return f"{self.title} | {self.author}"


    def get_absolute_url(self):
        """
        addpost sayfasında postu kaydederken hata aldık
        ve o hatada get_absolute_urlin eksik olduğunu söylediği için
        bu fonksiyonu ekledik.
        get_absolute_url, Django'da modellerin özel bir yöntemidir.
        return reverse('article-detail', args=(str(self.id)))
        """
        return reverse('theblog:home')


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

ablog/theblog/forms.py
from django import forms
from theblog.models import Post, Category, Comment

# choices = [('coding', 'coding'), ('sports', 'sports'), ('entertainment', 'entertainment'),]
choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    """
    Post modeli fieldlarını forma dönüştürmek için.
    ModelForm sınıfı, bir modelin bir veya daha fazla alanını kullanarak otomatik
    olarak bir form oluşturmak için kullanılır.
    Bu, aynı veri modelini hem veritabanında hem de web formunda kullanarak
    tutmanıza olanak tanır.
    """

    class Meta:
        """
        Meta sınıfı, formun hangi model sınıfını kullanacağını ve
        hangi alanların formda görüneceğini belirler.
        """

        model = Post
        fields = ('title', 'title_tag', 'category', 'body', 'header_image') #authoru sildik.
        widgets = {
            """
            widgets -> styling stuff
            'class':'form-control' -> cssteki form classı atadık.
            'placeholder':'This is Title Placeholder Stuff' 
            -> yazmaya başlamadan önce görünen silik yazı.
            """
            
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'title_tag' : forms.TextInput(attrs={'class':'form-control'}),
            #'author': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'elder', 'type':'hidden'}),

            """
            'author' : forms.Select(attrs={'class':'form-control'}),
             yoruma aldık çünkü kullanıcının yeni bir post eklerken 
             başka bir kullanıcıyı seçmesini istemiyoruz.
            """
            
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class':'form-control'}),
        }

ablog/theblog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from theblog.models import Post, Category, Comment
from theblog.forms import PostForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
"""
ListView, bir modelin tüm öğelerini listeleyen bir genel görünüm sınıfıdır.
ListView, bir veritabanı sorgusunu otomatik olarak gerçekleştirir.
ListView, sıralama, sayfalama, filtreleme ve arama gibi işlevler için destek sağlar.

DetailView, bir model öğesinin ayrıntılarını görüntülemek için 
kullanılan bir genel görünüm sınıfıdır.
DetailView, belirli bir model öğesiyle çalışır ve o öğenin tüm özelliklerini, 
yani alanlarını görüntüleyebilir.

def home(request):
   return render(request, 'home.html', {})
"""
def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))

    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user.id)
    else:
        post.likes.add(request.user.id)

    return HttpResponseRedirect(reverse('theblog:article-detail', args=[str(pk)]))


class HomeView(ListView):
    # tüm blog postları homepagede listelemek istiyoruz.o yüzden listview
    model = Post
    template_name = 'home.html'
    ordering = ['-post_date']
    """
    ordering = ['-id']  -> son eklenen postun en üstte görünmesini sağlar.
    Post modelinde id alanı tanımlamamıza rağmen django bir model oluşturduğumuzda
    default olarak id atar. bu sayede id ile işlem yapabiliyoruz.
    """
    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        # stuff = get_object_or_404(Post, id=self.kwargs["pk"])
        # total_likes = stuff.total_likes()
        # context["total_likes"] = total_likes
        return context

"""
def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'category_list.html', {'cat_menu_list':cat_menu_list})
"""

def CategoryView(request, cats):
    category_posts = Post.objects.filter(category=cats.replace('-', ' '))
    return render(
        request, 'categories.html',
        {'cats':cats.title().replace('-', ' '), 'category_posts':category_posts}
    )


class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_details.html'

    # def get_context_data(self, **kwargs):
    #     stuff = get_object_or_404(Post, id=self.kwargs["pk"])
    #     total_likes = stuff.total_likes()
    #
    #     liked = False
    #     if stuff.likes.filter(id=self.request.user.id):
    #         liked=True

class AddPostView(CreateView):
    model = Post
    form_class = PostForm #formu buraya da ekledik
    template_name = 'add_post.html'
    """
    yoruma aldık çünkü artık form kullanacak ve
    PostFormda fieldları belirttik zaten.
    fields = '__all__' -> models.pydaki Post classının tüm fieldlerini getirir.
    fields = ('title', 'body') -> sadece title ve body kısmını gösterir.
    """

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'
    #fields = '__all__'
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('theblog:home')


class AddCategoryView(CreateView):
    model = Category
    #form_class = PostForm #bir tane alan olduğu için bunu kullanmadık
    fields = '__all__'
    template_name = 'add_category.html'


class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'update_post.html'
    #fields = ['title', 'title_tag', 'body']

    def get_form(self, form_class=None):
        """
        form_class parametresi, form sınıfını belirtir.
        Bu parametre, varsayılan olarak None olarak ayarlanır.
        """
        form = super().get_form(form_class)
        #form.fields.pop('author')
        # edit işlemi sırasında author alanını formdan çıkarır
        return form


class DeletePostView(DeleteView):
    """
    8000/article/1/remove sayfasında Delete Post! butonuna tıkladığımızda
    normalde bizi home page'e yönlendirmesi gerekir;
    (models.py'daki Post classındaki return reverse('home')'dan dolayı)
    Fakat DeletePostView'da bu işe yaramıyor.
    hata mesajında bizden success_url istiyor.
    delete işleminden sonra özellikle nereye gideceğini belirtmemiz gerekiyor.
    reverse bu aşamada işe yaramıyor bu yüzden
    reverse_lazy'yi import etmemiz gerekiyor.
    """
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('theblog:home')

ablog/theblog/templates/add_category.html
{% extends 'base.html' %}
{% block title %}Create A New Blog Category!{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Add Category...</h1>
        <br><br>
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-secondary">
                    Add
                </button>
            </form>
        </div>
    {% else %}
        You're not allowed here! Please login.
    {% endif %}
{% endblock %}

ablog/theblog/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Comment On Blog Post{% endblock %}

{% block content %}
        <h1>Add Comment</h1>
        <br><br>
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-secondary">
                    Push the comment
                </button>
            </form>
        </div>
{% endblock %}

ablog/theblog/templates/add_post.html
{% extends 'base.html' %}
{% block title %}Create A New Blog Post!{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Add Post...</h1>
        <br><br>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-secondary">
                    Post
                </button>
            </form>
        </div>
        <!--
        <script>
            var name = "{{ user.id }}";
            document.getElementById("elder").value = name;
        </script>
        -->
    {% else %}
        You're not allowed here! Please login.
    {% endif %}
{% endblock %}

ablog/theblog/templates/article_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ post.title_tag }} {% endblock %}

{% block content %}
<!--
current user: {{ user.id }} <br>
post author: {{ post.author.id }}
-->
    <h1>{{ post.title }}</h1>
    <small>By:
        {{ post.author.first_name }}
        {{ post.author.last_name }} -
        {{ post.post_date }}

        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                - <a href="{% url 'theblog:update_post' post.pk %}">
                    (Edit)
                </a> -

                <a href="{% url 'theblog:delete_post' post.pk %}">
                    (Delete)
                </a>
            {% endif %}
        {% endif %}
    </small>
    <br>
    <hr>
    <br>
    {%  if post.header_image %}
        <img src="{{ post.header_image.url }}" width="300" height="300">
    <br><br>
    {% endif %}
    {{ post.body|safe }}
    <hr>
    <br>
    <form action="{% url 'theblog:like_post' post.pk %}" method="POST">
        {% csrf_token %}
        <!-- <button type="submit", name="post_id",
                value="{{ post.id }}", class="btn
                 {% if user in post.likes.all %}
                 btn-primary btn-sm
                {% else %}
                btn-outline-primary
                {% endif %}
                btn-sm">
            Like
        </button> --> <!-- - {{ total_likes }} Likes -->
        {% if user.is_authenticated %}
            {% if user in post.likes.all %}
                <button type="submit", name="post_id",
                        value="{{ post.id }}", class="btn btn-danger btn-sm">
                    Unlike
                </button>
            {% else %}
                <button type="submit", name="post_id",
                        value="{{ post.id }}", class="btn btn-primary btn-sm">
                Like
                </button>
            {% endif %}
        {% else %}
            <small><a href="{% url 'login' %}">
                Login to Like
            </a></small>
        {% endif %}

        - {{ post.likes.count }} Likes
    </form>

    <br><br>
    <div class="card mb-3" >
      <div class="row g-0">
        <div class="col-md-2">
    {% if post.author.profile.profile_pic %}
            <img src="{{ post.author.profile.profile_pic.url }}" class="card-img">
    {% else %}
            <img src="{% static "theblog/images/default_pp.png" %}" class="card-img">
    {% endif %}
        </div>
        <div class="col-md-10">
          <div class="card-body">
            <h5 class="card-title">{{ post.author.first_name }} {{ post.author.last_name }}
            - <a href="{% url 'members:show_profile_page' post.author.profile.id %}">User's Profile</a>
            </h5>

            <p class="small text-muted">
                {% if post.author.profile.website_url %}
                <a href="{{ post.author.profile.website_url }}">| Website</a>
                {% endif %}

                {% if post.author.profile.facebook_url %}
                <a href="{{ post.author.profile.facebook_url }}">Facebook</a> |
                {% endif %}

                {% if post.author.profile.twitter_url %}
                <a href="{{ post.author.profile.twitter_url }}">Twitter</a> |
                {% endif %}

                {% if post.author.profile.instagram_url %}
                <a href="{{ post.author.profile.instagram_url }}">Instagram</a> |
                {% endif %}

                {% if post.author.profile.pinterest_url %}
                <a href="{{ post.author.profile.pinterest_url }}">Pinterest</a> |
                {% endif %}
                {% if post.author.profile.mail_to %}
                <a href="mailto:{{ post.author.profile.mail_to }}">Mail</a> |
                {% endif %}

            </p>
            <p class="card-text">{{ post.author.profile.bio }}</p>
          </div>
        </div>
      </div>
    </div>
    <br>
    <h2>Comments</h2>
    {% if not post.comments.all %}
        No Comments Yet... <br><a href="{% url 'theblog:add_comment' post.pk %}">Add One</a>
    {% else %}
        <a href="{% url 'theblog:add_comment' post.pk %}">Add Comment</a>
        <br><br>
        {% for comment in post.comments.all %}
            <strong>{{ comment.name }} - {{ comment.date_added }}</strong>
            <br>
            {{ comment.body }}
            <br><br>
        {% endfor %}
    {% endif %}
    <br><br>
{% endblock %}

ablog/theblog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous"
    >

    <title>
        {% block title %}My Blog!{% endblock %}
    </title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'theblog:home' %}">
          My Blog!
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <!-- Category Menu Code -->
            {% if cat_menu %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"
                   id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                    {% for item in cat_menu %}

                        <a class="dropdown-item"
                           href="{% url 'theblog:category' item|slugify %}">
                            {{ item }}
                        </a>
                        <!--
                        <a class="dropdown-item" href="/theblog:category">
                            {{ item }}
                        </a>
                        -->
                    {% endfor %}
                </div>
            </li>
            {% endif %}
          {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'theblog:add_post' %}">
                    Add Post
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'theblog:add_category' %}">
                    Add Category
                </a>
            </li>
              
          {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:register' %}">
                    Register
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">
                    Login
                </a> <!-- buradaki login ana url'den geliyor-->
            </li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    {{ user.first_name }} {{ user.last_name }}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'members:edit_profile' %}">Edit Settings</a></li>
                    {% if user.profile.id %}
                        <li><a class="dropdown-item" href="{% url 'members:edit_profile_page' user.profile.id %}">Edit Profile Page</a></li>
                        <li><a class="dropdown-item" href="{% url 'members:show_profile_page' user.profile.id %}">Show Profile Page</a></li>
                    {% else %}
                        <li><a class="dropdown-item" href="{% url 'members:create_profile_page' %}">Create Profile Page</a></li>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'logout' %}">
                        Logout
                    </a>
                  </ul>
                </li>
            </ul>
        {% endif %}
      </div>
    </nav>
    <br>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
  </body>
</html>

ablog/theblog/templates/categories.html
{% extends 'base.html' %}

{% block content %}
    {% if category_posts %}
        <h1>{{ cats }}</h1>

        <ul>
        {% for post in category_posts %}
             <li>
                <a href="{% url 'theblog:article-detail' post.pk  %}">
                    {{ post.title }} -
                </a>
                {{ post.author.first_name }}
                {{ post.author.last_name }} /
                {{ post.post_date }}

                {% if user.is_authenticated %}
                    - <small>
                        <a href="{% url 'theblog:update_post' post.pk %}">
                            Edit
                        </a> -
                        <a href="{% url 'theblog:delete_post' post.pk %}">
                            Delete
                        </a>
                    </small>
                {% endif %}
                <br>
                {{ post.body|slice:":200" }}
                <!-- anasayfada maks. 200 karakter gösterir -->
             </li>
        {% endfor %}
        </ul>
    {% else %}
        <h2>Sorry this page doesn't exist...</h2>
    {% endif %}
{% endblock %}

ablog/theblog/templates/category_list.html
{% extends 'base.html' %}
{% block title %} Blog Categories {% endblock %}

{% block content %}

    <h1>Blog Categories</h1>

    {% for item in cat_menu_list %}
        <h4><a class="dropdown-item"
           href="{% url 'theblog:category-list' item|slugify %}">
            {{ item }}
        </a></h4>
    {% endfor %}

{% endblock %}

ablog/theblog/templates/delete_post.html
{% extends 'base.html' %}
{% block title %}Delete Blog Post{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <!-- eğer giriş yapan kullanıcı ile postu oluşturan
            kullanıcı aynı ise bu işlemi gerçekleştirebilsin
            bu if satırını article_tails, update_post
            ve home.html'de de kullandık.-->
            <h1>Delete Post...</h1>
            <br><br>
            <h3>Delete: {{ post.title }}</h3>
            <br>
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    <!--
                    {{ form.as_p }}
                    yorum satırına aldık çünkü formun tamamına ihtiyacımız yok,
                    çünkü hiçbir şey update vs. etmiycez tek ihtiyacımız olan
                    bunu silmekten emin misin diyen buton
                    -->
                    <strong>Are you sure?</strong>
                    <br><br>
                    <button class="btn btn-secondary">
                        Delete Post!
                    </button>
                    <br><br>
                    <a href="{% url 'theblog:home' %}" class="btn btn-secondary">
                        No, go back
                    </a>
                </form>
            </div>
        {% else %}
            You're not allowed here!
        {% endif %}
    {% else %}
        You're not allowed here! Please login.
    {% endif %}
{% endblock %}

ablog/theblog/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Posts</h1>
    <ul>
        {% for post in object_list %}
            <li>
                <a href="{% url 'theblog:article-detail' post.pk  %}">
                    {{ post.title }}
                </a>
                -
                <a href="{% url 'theblog:category' post.category|slugify  %}">
                    {{ post.category }}
                </a>
                - {{ post.author.first_name }}
                {{ post.author.last_name }} /
                {{ post.post_date }}

                {% if user.is_authenticated %}
                    {% if user.id == post.author.id %}
                        - <small>
                            <a href="{% url 'theblog:update_post' post.pk %}">
                                Edit
                            </a> -
                            <a href="{% url 'theblog:delete_post' post.pk %}">
                                Delete
                            </a>
                        </small>
                    {% endif %}
                {% endif %}
                <br>
                {{ post.body|slice:":200"|safe|striptags }}
                <!-- anasayfada maks. 200 karakter gösterir -->
            </li>
        {% endfor %}
    </ul>
{% endblock %}

ablog/theblog/templates/update_post.html
{% extends 'base.html' %}
{% block title %}Edit Blog Post{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <h1>Update Post...</h1>
            <br><br>
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <button class="btn btn-secondary">
                        Update
                    </button>
                </form>
            </div>
        {% else %}
            You're not allowed here!
        {% endif %}
    {% else %}
        You're not allowed here! Please login.
    {% endif %}
{% endblock %}